using System.Collections.Generic;

namespace CodeBrix.Ollama.ModelRunner;

/// <summary>Experimental rolling musical context for successive MuseCoco streaming sections.</summary>
/// <remarks>
/// Create with MuseCocoMusicModel.CreateContinuation and reuse with that model's
/// GenerateContinuationStreamingAsync. Events across sections share one absolute MIDI timeline
/// and stable channels. This is experimental: transitions and long-form musical quality need listening tests.
/// Cancellation, failure or early enumeration disposal invalidates this context; create a new one afterward.
/// </remarks>
public sealed class MuseCocoContinuation
{
    internal MuseCocoContinuation(MuseCocoMusicModel owner, int contextBars)
    {
        Owner = owner;
        ContextBars = contextBars;
    }

    internal MuseCocoMusicModel Owner { get; }
    internal Remigen2StreamDecoder Decoder { get; } = new Remigen2StreamDecoder();
    internal int[] Prompt { get; private set; } = System.Array.Empty<int>();
    internal bool Invalid { get; set; }

    /// <summary>Maximum recent completed bars replayed as context for the next section.</summary>
    public int ContextBars { get; }

    /// <summary>Number of retained music tokens that the next request will replay as a prompt.</summary>
    public int ContextTokenCount => Prompt.Length;

    /// <summary>Number of normally completed section enumerations, including an empty EOS response.</summary>
    public int CompletedSections { get; private set; }

    /// <summary>Tokens generated by the last completed section, excluding replayed context and EOS.</summary>
    public int LastGeneratedTokenCount { get; private set; }

    /// <summary>Absolute start tick of the next section, at 480 ticks per quarter note.</summary>
    public long NextTick => Decoder.BarTick;

    internal void Complete(IReadOnlyList<int> generated, IReadOnlyList<string> vocabulary,
        IReadOnlyDictionary<string, int> tokenIds)
    {
        if (generated.Count != 0)
            Prompt = Remigen2ContextWindow.Take(Prompt, generated, vocabulary, tokenIds, ContextBars);
        LastGeneratedTokenCount = generated.Count;
        CompletedSections++;
    }
}
